### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by dsamojlenko**
# Summary | Résumé

Updates the readme to include information about the Outbreaks feature and Business Registration Website, as well as improve and streamline some of the technical and development instructions.

### CODE REVIEW

**Review by dorianjp — APPROVED** [review]
more organized, nice

**Comment by sylviamclaughlin** [comment]
This looks great Dave! I think it is much more clearer now the way you have organized the instructions and added table of contents. I really don't have any suggestions to improve the readme, since I think it looks great.

**Comment by nchoquet** [comment]
Hi Dave,

here is the French translation of the updated Covid Alert Portal Readme. Let me know if you have any questions!

[README_update-en_ca-fr_ca-R-C.md](https://github.com/cds-snc/covid-alert-portal/files/7170824/README_update-en_ca-fr_ca-R-C.md)

**Comment by sylviamclaughlin** [comment]
I am closing this PR since it was essentially replicated in PR #691. Updated content and its associated french translations have been merged in main.

**Pull request closed without merging**
