### PR TITLE
Update "welcome", "quick guide", "account", and "manage team" pages to V6 content

### PR DESCRIPTION
**Pull request by pcraig3**
This PR updates the content for the first 3 rows of the Figma file:

- the "welcome" page
- the "quick guide" page
- the "contact" pages
- the "account" pages (including the "edit" pages)
- the "manage team" pages, eg
  - "manage team": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/profiles/
  - "add new account": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite/
  - "invite complete" (you need to send an invite to see the title): https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite-complete/
  - "check invitations": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite/list/

I don't really want to screenshot it because this is more easily reviewed by actually looking through the application or bu looking through the files themselves.

### CODE REVIEW

**Comment by YedidaZalik** [comment]
@pcraig3 on the Welcome page, the heading " Welcome to the portal" is missing in English and French

**Comment by YedidaZalik** [comment]
@pcraig3 Please change - By comparing 3 stats, we can learn how people use the app and improve the COVID Alert system. 
To - By comparing 3 stats, we can learn how people use the app. 
(so pls remove "and improve the COVID Alert system".)
I'll ask Elise for the French.

**Comment by YedidaZalik** [comment]
@pcraig3  Contact - success looks good!

**Comment by YedidaZalik** [comment]
@pcraig3 In French  on both welcome page and quick guide,  for the part that says in English
"By comparing 3 stats, we can learn how people use the app. We need the number of:"
Please use in French
Certaines statistiques nous renseignent sur la façon dont les personnes utilisent l’application. Nous avons besoin de connaître :

**Comment by pcraig3** [comment]
@YedidaZalik, Okay! Made the changes.

**Comment by pcraig3** [comment]
@YedidaZalik, I also looked over the 4th row in the figma docs around adding/removing accounts and invites

- the "manage team" pages, eg
  - "manage team": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/profiles/
  - "add new account": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite/
  - "invite complete" (you need to send an invite to see the title): https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite-complete/
  - "check invitations": https://covid-alert-v6-welcome-d6eubs7.herokuapp.com/en/invite/list/

**Comment by YedidaZalik** [comment]
Looks good!
Thanks @pcraig3

**Review by bryan-robitaille — APPROVED** [review]
Looks good to me

**Pull request merged**
