### PR TITLE
Remove basicauth from Production

### PR DESCRIPTION
**Pull request by dsamojlenko**
# Summary | Résumé

Basicauth was meant as a temporary measure on the Production registration site. This removes it in preparation for launch.

### CODE REVIEW

**Review by dorianjp — COMMENTED** [review]
@dsamojlenko 
Do we also want to get rid of the override middleware class as well?

**Comment by dsamojlenko** [comment]
> @dsamojlenko
> Do we also want to get rid of the override middleware class as well?

Good catch, removed it.

**Review by dorianjp — APPROVED** [review]
lgtm

**Comment by dsamojlenko** [comment]
Closing this as we will be decommissioning the Registration site in Production.

**Pull request closed without merging**
