### PR TITLE
new fields and support for venue type in survey

### PR DESCRIPTION
**Pull request by dorianjp**
# Summary | Résumé

Trello
https://trello.com/c/YzBmJN60/870-add-venue-type-tags-to-survey-urls

* new fields to support dynamic query param builder for survey url
* concatenate venue types for multiple values

# Test instructions | Instructions pour tester la modification

* Migrate new fields
* Ensure registrant_id_url_param and venue_tag_url_param are entered in django admin, "Regid" and "vt" for current surveys
* Ensure both append_registrant.. and append_venue_tag_ind are True for any test surveys
* Send survey via django admin

### CODE REVIEW

**Comment by dorianjp** [comment]
[Add venue type tags to survey URLs](https://trello.com/c/YzBmJN60/870-add-venue-type-tags-to-survey-urls)

**Comment by dorianjp** [comment]
@dsamojlenko, the new fields are there to separate query params from the survey url with the new potential for using venue tags put into place. Keeping it this way permits the survey to not be hardcoded into a one-trick-pony for a highly specific url structure for pretty much the same amount of work as baking the query params in.

**Review by sylviamclaughlin — APPROVED** [review]
I tested out the branch and it works great.

**Review by dsamojlenko — APPROVED** [review]
beauty

**Pull request merged**
