### PR TITLE
Add signal to remove pending announcement creation on user deletion

### PR DESCRIPTION
**Pull request by bryan-robitaille**
This PR ensure that when new announcements are created during a HealthcareUser's cascade deletion that those new announcements are also deleted before the DB update is done.

### CODE REVIEW

**Review by pcraig3 — CHANGES_REQUESTED** [review]
Can you write a test for this? 

(Hint, there's one over here you can use: https://github.com/cds-snc/covid-alert-portal/commit/7171c0a88acc4ad8d21b00b0617d72c0e735b937#diff-0e7f46abe26fa8a6b8c0be01a304f2bf3d6810f3092b97b4765fb406755cd8d4)

**Review by pcraig3 — APPROVED** [review]
👍  nice! hopefully all bugs we can squash them before they go to prod.

**Comment by bryan-robitaille** [comment]
Test now included

**Review by pcraig3 — CHANGES_REQUESTED** [review]
Wait!

**Comment by bryan-robitaille** [comment]
Ok

**Review by pcraig3 — CHANGES_REQUESTED** [review]
Since this isn't in the `profiles` module, we should use `get_user_model` instead of hardcoding the HealthcareUser.

eg,

```py
from django.contrib.auth import get_user_model
User = get_user_model()
```

**Review by pcraig3 — APPROVED** [review]
once tests are green, let's merge.

**Pull request merged**
