### PR TITLE
Moves the validation error on confirmation fields to the first field

### PR DESCRIPTION
**Pull request by PierrePaul**
Moves the error message of all fields that needs a confirmation (phone_number, password) into the first field.

https://trello.com/c/ZR6ePNoX/196-a11y-password-validation-error-during-signup-should-be-on-the-first-password-field

Screenshot_2020-09-02 Error Change your mobile phone number — COVID Alert Portal

Screenshot_2020-09-02 Error Create account — COVID Alert Portal

Screenshot_2020-09-02 Error Create account — COVID Alert Portal(1)

### CODE REVIEW

**Comment by pcraig3** [comment]
A couple comments on this one:

1. It looks like you can reset your password through your account with 2 passwords that don't match. (The first one will be used). Also, you are logged out immediately after changing your password, which is maybe not the intended behaviour.

2. On the "reset password" page, the alert is still on the second field.

Screen Shot 2020-09-03 at 11 06 14 AM

**Review by pcraig3 — CHANGES_REQUESTED** [review]
I think the code is good now (it works!!), but can you push a patch version update as well and then merge.

Feels like a bugfix to me — actually several.
-  making the system work better for some users
- don't lose the session after password changes
- updating passwords now looks for mismatches

**Comment by PierrePaul** [comment]
I updated the changelog and version. https://github.com/cds-snc/covid-alert-portal/pull/206/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR15

I didnt mention the `updating passwords now looks for mismatches`, since it was a bug introduced by the PR.

**Comment by pcraig3** [comment]
Ah, parfait!

**Review by pcraig3 — APPROVED** [review]
Approve! Thanks for this update!

**Pull request merged**
