### PR TITLE
new page created and help page updated with new content

### PR DESCRIPTION
**Pull request by dorianjp**
Trello:
https://trello.com/c/yWjT16BR/736-create-a-stand-alone-displaying-the-poster-page
https://trello.com/c/4GwGDUxo/743-update-support-page-to-become-help-and-information

* Renamed qr support page to help and all references/links to page/code
* New content for help page
* New page linked off help page -> How to display your COVID Alert poster
* Footer updated for new links
* New url /display for new how to display page

### CODE REVIEW

**Comment by dorianjp** [comment]
[Create a stand-alone 'Displaying the Poster' Page](https://trello.com/c/yWjT16BR/736-create-a-stand-alone-displaying-the-poster-page)

**Comment by dorianjp** [comment]
[Update support page to become "Help and information"](https://trello.com/c/4GwGDUxo/743-update-support-page-to-become-help-and-information)

**Comment by dorianjp** [comment]
[Update the Footer links](https://trello.com/c/dGBMjrPl/749-update-the-footer-links)

**Comment by dsamojlenko** [comment]
Just missing the `< Home` link on the main Help and information page.

image

**Review by dsamojlenko — APPROVED** [review]
LGTM

**Pull request merged**
